In [3]:
!pip install Numpy

In [4]:
#importing numpy
import numpy as np
#creating numpy
a = np.array([1,2,3])  #1D
b = np.array([(2.3,1,3),(7,8,9)],dtype = float)
c = np.array([[(2.3,1,3),(7,8,9)],[(1.5,2.5,3.5),(6,4.9,2)]],dtype = float)
print(a)
print(b)
print(c)

[1 2 3]
[[2.3 1.  3. ]
 [7.  8.  9. ]]
[[[2.3 1.  3. ]
  [7.  8.  9. ]]

 [[1.5 2.5 3.5]
  [6.  4.9 2. ]]]


In [18]:
#initial placeholders
#create an array of zeros
np.zeros((3))   #creating 1D array

array([0., 0., 0.])

In [20]:
np.zeros((2,3))  #creating 2D array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
#create an array of ones
np.ones((2,3,4))  #shape, rows,cols

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [26]:
#creating an array of evenly spaced values
d = np.arange(1,40,4)   #n-1 = (4-1 = 2)
print(d)

[ 1  5  9 13 17 21 25 29 33 37]


In [42]:
#create an array of evenly spaced values 
np.linspace(10,25,8)

array([10.        , 12.14285714, 14.28571429, 16.42857143, 18.57142857,
       20.71428571, 22.85714286, 25.        ])

In [44]:
#create a constant array
#create 1D array
e = np.full((5),10)
print(e)
print(e.ndim)

[10 10 10 10 10]
1


In [48]:
#create 2D array
e = np.full((5,4),55)
print(e)
print(e.ndim)

[[55 55 55 55]
 [55 55 55 55]
 [55 55 55 55]
 [55 55 55 55]
 [55 55 55 55]]
2


In [52]:
#create 3D array
e = np.full((6,4,3),8)
print(e)
print(e.ndim)

[[[8 8 8]
  [8 8 8]
  [8 8 8]
  [8 8 8]]

 [[8 8 8]
  [8 8 8]
  [8 8 8]
  [8 8 8]]

 [[8 8 8]
  [8 8 8]
  [8 8 8]
  [8 8 8]]

 [[8 8 8]
  [8 8 8]
  [8 8 8]
  [8 8 8]]

 [[8 8 8]
  [8 8 8]
  [8 8 8]
  [8 8 8]]

 [[8 8 8]
  [8 8 8]
  [8 8 8]
  [8 8 8]]]
3


In [58]:
#create a 2*2 identity matrix
f = np.eye(4)
print(f)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [62]:
#create an array with random values
np.random.random((4,5))  #row,columns

array([[0.18478674, 0.92555527, 0.96171253, 0.58723292, 0.85820582],
       [0.81282752, 0.20628411, 0.68413132, 0.7369891 , 0.1231294 ],
       [0.79214971, 0.20894245, 0.716696  , 0.02223941, 0.57534763],
       [0.64455881, 0.62463597, 0.69861354, 0.17730574, 0.43612525]])

In [68]:
np.random.randint(1,15)

11

In [70]:
#to find shape of an array 
arr = np.array([[1,2,3,4],
               [2,3,4,5],
               [3,4,5,6],
               [7,8,5,6]])
print(arr.shape)

(4, 4)


In [72]:
#to find no of elements in array
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(arr.size)

9


In [74]:
#to find len of array
arr = np.array([[1,2,3,4],
                [4,5,6,7],
                [5,6,7,8],
                [3,4,5,2],
                [2,8,9,3]])
len(arr)

5

In [5]:
#Access array elements
arr = np.array([1,2,3,4])
print(arr[0])

1


In [9]:
#Adding two index position
arr = np.array([1,2,3,4,5,6,7])
print(arr[3]-arr[1]+arr[5]+arr[4])    #1D array

13


In [11]:
#Access 2D array
arr = np.array([[1,2,3,4],
                [2,9,8,7],
                [3,4,5,6],
                [6,6,7,4]])  #(1D,elements)
print(arr[2,2])

5


In [13]:
#Access 3-D array
arr = np.array([[[1,2,3],[2,3,4]],
                [[3,4,5],[4,5,6]],
                [[5,6,7],[8,6,9]],
                [[2,5,8],[7,8,2]]])
#Access by index
print(arr[2,1,2])  #2D,1D,element

9


In [27]:
#Data types
#string
arr = np.array([1,2,3,4],dtype = 'S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [35]:
#int
arr = np.array([1,2,3,4],dtype = 'i')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [37]:
#float to integer
arr = np.array([1.9,2.3,1.25,2.25])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 1 2]
int32


In [39]:
#int to boolean
arr = np.array([1,0,3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [41]:
#int to float
arr = np.array([1,2,3,4])
newarr = arr.astype('f')
print(newarr)
print(newarr.dtype)

[1. 2. 3. 4.]
float32


In [53]:
#copy method
arr = np.array([1,7,2,0,3,4])
z = arr.copy()
arr[3] = 44
print(arr)
print(z)

[ 1  7  2 44  3  4]
[1 7 2 0 3 4]


In [55]:
#view method
arr = np.array([1,5,8,7,6,4,3])
x = arr.view()
arr[3] = 79
print(arr)
print(x)

[ 1  5  8 79  6  4  3]
[ 1  5  8 79  6  4  3]


In [57]:
#size
arr = np.array([[1,2,3,4,5],
               [3,5,4,2,1]])
print(arr.shape)

(2, 5)


In [65]:
#Reshaping arrays
#converting 1D array to 2D array
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
print(arr.size)
newarr = arr.reshape(4,4)
print(newarr)

16
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [71]:
#converting 1D array to 3D array
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
newarr = arr.reshape(2,4,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [75]:
#converting 2D array to 1D array
arr = np.array([[1,2,3,4],
                [2,3,4,5],
                [3,4,5,6],
                [4,5,6,7]])
newarr = arr.reshape(16)
print(newarr)

[1 2 3 4 2 3 4 5 3 4 5 6 4 5 6 7]


In [81]:
#converting 2D array to 3D array
arr = np.array([[1,2,3,4],
                [2,3,4,5],
                [3,4,5,6],
                [4,5,6,7]])
newarr = arr.reshape(4,2,2)
print(newarr)


[[[1 2]
  [3 4]]

 [[2 3]
  [4 5]]

 [[3 4]
  [5 6]]

 [[4 5]
  [6 7]]]


In [85]:
#converting 3D array to 1D array
arr = np.array([[[1,2,3],[3,4,5]],
                [[3,2,5],[2,5,6]],
                [[4,5,6],[7,6,5]]])
newarr = arr.reshape(18)
print(newarr)
               

[1 2 3 3 4 5 3 2 5 2 5 6 4 5 6 7 6 5]


In [95]:
#converting 3D array to 2D array
arr = np.array([[[1,2,3],[3,4,5]],
                [[3,2,5],[2,5,6]],
                [[4,5,6],[7,6,5]]])
newarr = arr.reshape(3,6)
print(newarr) 

[[1 2 3 3 4 5]
 [3 2 5 2 5 6]
 [4 5 6 7 6 5]]


In [154]:
#Arthmetic operations on 1D array
#Addition
arr1 = np.array([1,2,3,4,89])
arr2 = np.array([7,27,68,16,79])
print(arr1+arr2)
np.add(arr1,arr2)

[  8  29  71  20 168]


array([  8,  29,  71,  20, 168])

In [160]:
#Subtraction 
print(arr1-arr2)
np.subtract(arr1,arr2)

[ -6 -25 -65 -12  10]


array([ -6, -25, -65, -12,  10])

In [162]:
#multiplication
print(arr1*arr2)
np.multiply(arr1,arr2)

[   7   54  204   64 7031]


array([   7,   54,  204,   64, 7031])

In [164]:
#division
print(arr1/arr2)
np.divide(arr1,arr2)

[0.14285714 0.07407407 0.04411765 0.25       1.12658228]


array([0.14285714, 0.07407407, 0.04411765, 0.25      , 1.12658228])

In [170]:
#floor division
print(arr1//arr2)
np.floor_divide(arr1,arr2)

[0 0 0 0 1]


array([0, 0, 0, 0, 1])

In [174]:
#modulus
print(arr1%arr2)
np.mod(arr1,arr2)

[ 1  2  3  4 10]


array([ 1,  2,  3,  4, 10])

In [190]:
#exponential
arr1 = np.array([1, 2, 3, 4, 89])
arr2 = np.array([7, 27, 68, 16, 79])

exp_arr1 = np.exp(arr1)     #e^x
exp_arr2 = np.exp(arr2)

print("Exponential of arr1:", exp_arr1)
print("Exponential of arr2:", exp_arr2)

Exponential of arr1: [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 4.48961282e+38]
Exponential of arr2: [1.09663316e+03 5.32048241e+11 3.40427605e+29 8.88611052e+06
 2.03828107e+34]


In [195]:
#squart root
print(np.sqrt(arr1))
print(np.sqrt(arr2))

[1.         1.41421356 1.73205081 2.         9.43398113]
[2.64575131 5.19615242 8.24621125 4.         8.88819442]


In [197]:
#Arthmetic operation on 2D array
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[5, 7, 8], [4, 9, 6]])

add_result = x + y
sub_result = x - y
mul_result = x * y
div_result = x / y
floor_result = x//y
mod_result = x%y

exp_x = np.exp(x)
exp_y = np.exp(y)

sqrt_x = np.sqrt(x)
sqrt_y = np.sqrt(y)
print("Addition:\n", add_result)
print("Subtraction:\n", sub_result)
print("Multiplication:\n", mul_result)
print("Division:\n", div_result)
print("floor division:\n",floor_result)
print("modulus:\n",mod_result)
print("Exponential of x:\n", exp_x)
print("Exponential of y:\n", exp_y)
print("square root of x:\n", sqrt_x)
print("square root of y:\n", sqrt_y)

Addition:
 [[ 6  9 11]
 [ 8 14 12]]
Subtraction:
 [[-4 -5 -5]
 [ 0 -4  0]]
Multiplication:
 [[ 5 14 24]
 [16 45 36]]
Division:
 [[0.2        0.28571429 0.375     ]
 [1.         0.55555556 1.        ]]
floor division:
 [[0 0 0]
 [1 0 1]]
modulus:
 [[1 2 3]
 [0 5 0]]
Exponential of x:
 [[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
Exponential of y:
 [[ 148.4131591  1096.63315843 2980.95798704]
 [  54.59815003 8103.08392758  403.42879349]]
square root of x:
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
square root of y:
 [[2.23606798 2.64575131 2.82842712]
 [2.         3.         2.44948974]]


In [199]:
#Arthmetic operation on 3D array
x = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
y = np.array([[[5, 7, 8], [4, 9, 6]], [[3, 2, 1], [8, 7, 5]]])

add_result = x + y
sub_result = x - y
mul_result = x * y
div_result = x / y
floor_result = x//y
mod_result = x%y

exp_x = np.exp(x)
exp_y = np.exp(y)

sqrt_x = np.sqrt(x)
sqrt_y = np.sqrt(y)
print("Addition:\n", add_result)
print("Subtraction:\n", sub_result)
print("Multiplication:\n", mul_result)
print("Division:\n", div_result)
print("floor division:\n",floor_result)
print("modulus:\n",mod_result)
print("Exponential of x:\n", exp_x)
print("Exponential of y:\n", exp_y)
print("square root of x:\n", sqrt_x)
print("square root of y:\n", sqrt_y)

Addition:
 [[[ 6  9 11]
  [ 8 14 12]]

 [[10 10 10]
  [18 18 17]]]
Subtraction:
 [[[-4 -5 -5]
  [ 0 -4  0]]

 [[ 4  6  8]
  [ 2  4  7]]]
Multiplication:
 [[[ 5 14 24]
  [16 45 36]]

 [[21 16  9]
  [80 77 60]]]
Division:
 [[[0.2        0.28571429 0.375     ]
  [1.         0.55555556 1.        ]]

 [[2.33333333 4.         9.        ]
  [1.25       1.57142857 2.4       ]]]
floor division:
 [[[0 0 0]
  [1 0 1]]

 [[2 4 9]
  [1 1 2]]]
modulus:
 [[[1 2 3]
  [0 5 0]]

 [[1 0 0]
  [2 4 2]]]
Exponential of x:
 [[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
  [5.45981500e+01 1.48413159e+02 4.03428793e+02]]

 [[1.09663316e+03 2.98095799e+03 8.10308393e+03]
  [2.20264658e+04 5.98741417e+04 1.62754791e+05]]]
Exponential of y:
 [[[1.48413159e+02 1.09663316e+03 2.98095799e+03]
  [5.45981500e+01 8.10308393e+03 4.03428793e+02]]

 [[2.00855369e+01 7.38905610e+00 2.71828183e+00]
  [2.98095799e+03 1.09663316e+03 1.48413159e+02]]]
square root of x:
 [[[1.         1.41421356 1.73205081]
  [2.         2.23

In [201]:
#sorting array
arr = np.array([5,7,10,51,98])
np.sort(arr)

array([ 5,  7, 10, 51, 98])

In [203]:
#slicing array
#slicing 1D array
arr = np.array([2,15,17,85,25,99,57,34,44])
n = len(arr)
print(arr[1:7])
print(arr[:n-1])
print(arr[7:])

[15 17 85 25 99 57]
[ 2 15 17 85 25 99 57 34]
[34 44]


In [205]:
#negative slicing
arr = np.array([2,15,17,85,25,99,57,34,44])
n = len(arr)
print(arr[:])
print(arr[-2:n-1])
print(arr[::3])
print(arr[1:9:3])

[ 2 15 17 85 25 99 57 34 44]
[34]
[ 2 85 57]
[15 25 34]


In [207]:
#slicing 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[1,0: ])

[4 5 6]


In [209]:
#slicing 3D array
arr = np.array([[[1, 2, 3], [4, 5, 6]], 
                [[7, 8, 9], [10, 11, 12]]])
print(arr[0:6,1])

[[ 4  5  6]
 [10 11 12]]
