In [3]:
!pip install Numpy

In [9]:
#importing numpy
import numpy as np
#creating numpy
a = np.array([1,2,3])  #1D
b = np.array([(2.3,1,3),(7,8,9)],dtype = float)
c = np.array([[(2.3,1,3),(7,8,9)],[(1.5,2.5,3.5),(6,4.9,2)]],dtype = float)
print(a)
print(b)
print(c)

[1 2 3]
[[2.3 1.  3. ]
 [7.  8.  9. ]]
[[[2.3 1.  3. ]
  [7.  8.  9. ]]

 [[1.5 2.5 3.5]
  [6.  4.9 2. ]]]


In [18]:
#initial placeholders
#create an array of zeros
np.zeros((3))   #creating 1D array

array([0., 0., 0.])

In [20]:
np.zeros((2,3))  #creating 2D array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
#create an array of ones
np.ones((2,3,4))  #shape, rows,cols

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [26]:
#creating an array of evenly spaced values
d = np.arange(1,40,4)   #n-1 = (4-1 = 2)
print(d)

[ 1  5  9 13 17 21 25 29 33 37]


In [42]:
#create an array of evenly spaced values 
np.linspace(10,25,8)

array([10.        , 12.14285714, 14.28571429, 16.42857143, 18.57142857,
       20.71428571, 22.85714286, 25.        ])

In [44]:
#create a constant array
#create 1D array
e = np.full((5),10)
print(e)
print(e.ndim)

[10 10 10 10 10]
1


In [48]:
#create 2D array
e = np.full((5,4),55)
print(e)
print(e.ndim)

[[55 55 55 55]
 [55 55 55 55]
 [55 55 55 55]
 [55 55 55 55]
 [55 55 55 55]]
2


In [52]:
#create 3D array
e = np.full((6,4,3),8)
print(e)
print(e.ndim)

[[[8 8 8]
  [8 8 8]
  [8 8 8]
  [8 8 8]]

 [[8 8 8]
  [8 8 8]
  [8 8 8]
  [8 8 8]]

 [[8 8 8]
  [8 8 8]
  [8 8 8]
  [8 8 8]]

 [[8 8 8]
  [8 8 8]
  [8 8 8]
  [8 8 8]]

 [[8 8 8]
  [8 8 8]
  [8 8 8]
  [8 8 8]]

 [[8 8 8]
  [8 8 8]
  [8 8 8]
  [8 8 8]]]
3


In [58]:
#create a 2*2 identity matrix
f = np.eye(4)
print(f)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [62]:
#create an array with random values
np.random.random((4,5))  #row,columns

array([[0.18478674, 0.92555527, 0.96171253, 0.58723292, 0.85820582],
       [0.81282752, 0.20628411, 0.68413132, 0.7369891 , 0.1231294 ],
       [0.79214971, 0.20894245, 0.716696  , 0.02223941, 0.57534763],
       [0.64455881, 0.62463597, 0.69861354, 0.17730574, 0.43612525]])

In [68]:
np.random.randint(1,15)

11

In [70]:
#to find shape of an array 
arr = np.array([[1,2,3,4],
               [2,3,4,5],
               [3,4,5,6],
               [7,8,5,6]])
print(arr.shape)

(4, 4)


In [72]:
#to find no of elements in array
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(arr.size)

9


In [74]:
#to find len of array
arr = np.array([[1,2,3,4],
                [4,5,6,7],
                [5,6,7,8],
                [3,4,5,2],
                [2,8,9,3]])
len(arr)

5